-- ====================================================================
-- AgriShield AI — Supabase Database Schema & Realtime Setup Script
-- ====================================================================
-- Copy and run this script in your Supabase SQL Editor:
-- https://supabase.com/dashboard/project/_/sql

-- 1. SENSOR READINGS TABLE
CREATE TABLE IF NOT EXISTS public.sensor_readings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    temperature NUMERIC(5,2) NOT NULL,
    humidity NUMERIC(5,2) NOT NULL,
    moisture INTEGER NOT NULL,
    light INTEGER NOT NULL,
    water_level INTEGER NOT NULL,
    health_score INTEGER DEFAULT 100,
    pump_status TEXT CHECK (pump_status IN ('ON', 'OFF')) DEFAULT 'OFF',
    fan_status TEXT CHECK (fan_status IN ('ON', 'OFF')) DEFAULT 'OFF',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for fast telemetry queries
CREATE INDEX IF NOT EXISTS idx_sensor_readings_created_at ON public.sensor_readings(created_at DESC);

-- 2. DEVICE STATES TABLE
CREATE TABLE IF NOT EXISTS public.devices (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    pump TEXT CHECK (pump IN ('ON', 'OFF')) DEFAULT 'OFF',
    fan TEXT CHECK (fan IN ('ON', 'OFF')) DEFAULT 'OFF',
    light TEXT CHECK (light IN ('ON', 'OFF')) DEFAULT 'OFF',
    mode TEXT CHECK (mode IN ('Auto', 'Manual')) DEFAULT 'Auto',
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. ALERTS TABLE
CREATE TABLE IF NOT EXISTS public.alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL,
    message TEXT NOT NULL,
    status TEXT CHECK (status IN ('ACTIVE', 'ACKNOWLEDGED', 'RESOLVED')) DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. AUTOMATION RULES TABLE
CREATE TABLE IF NOT EXISTS public.automation_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    condition TEXT NOT NULL,
    threshold NUMERIC(5,2) NOT NULL,
    action TEXT NOT NULL,
    device TEXT NOT NULL,
    enabled BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. INITIAL SEED DATA
-- Seed single device state row if not exists
INSERT INTO public.devices (pump, fan, light, mode)
SELECT 'OFF', 'OFF', 'OFF', 'Auto'
WHERE NOT EXISTS (SELECT 1 FROM public.devices);

-- Seed default automation rules if not exists
INSERT INTO public.automation_rules (name, condition, threshold, action, device, enabled)
SELECT * FROM (VALUES
    ('High Temp Fan Activation', 'temp > 35°C', 35.0, 'Turn ON', 'fan', true),
    ('Low Moisture Irrigation', 'moisture < 30%', 30.0, 'Turn ON', 'pump', true)
) AS v(name, condition, threshold, action, device, enabled)
WHERE NOT EXISTS (SELECT 1 FROM public.automation_rules);

-- 6. ENABLE ROW LEVEL SECURITY (RLS) & PUBLIC PERMISSIONS
ALTER TABLE public.sensor_readings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.devices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.automation_rules ENABLE ROW LEVEL SECURITY;

-- Allow anonymous read & write for AgriShield dashboard & IoT devices
CREATE POLICY "Allow public read on sensor_readings" ON public.sensor_readings FOR SELECT USING (true);
CREATE POLICY "Allow public insert on sensor_readings" ON public.sensor_readings FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public read on devices" ON public.devices FOR SELECT USING (true);
CREATE POLICY "Allow public insert/update on devices" ON public.devices FOR ALL USING (true);

CREATE POLICY "Allow public read on alerts" ON public.alerts FOR SELECT USING (true);
CREATE POLICY "Allow public insert/update/delete on alerts" ON public.alerts FOR ALL USING (true);

CREATE POLICY "Allow public read on automation_rules" ON public.automation_rules FOR SELECT USING (true);
CREATE POLICY "Allow public all on automation_rules" ON public.automation_rules FOR ALL USING (true);

-- 7. ENABLE SUPABASE REALTIME PUBLICATION
ALTER PUBLICATION supabase_realtime ADD TABLE public.sensor_readings;
ALTER PUBLICATION supabase_realtime ADD TABLE public.devices;
ALTER PUBLICATION supabase_realtime ADD TABLE public.alerts;
